// Generated by gencpp from file yahboom_web_savemap_interfaces/WebSaveMapRequest.msg
// DO NOT EDIT!


#ifndef YAHBOOM_WEB_SAVEMAP_INTERFACES_MESSAGE_WEBSAVEMAPREQUEST_H
#define YAHBOOM_WEB_SAVEMAP_INTERFACES_MESSAGE_WEBSAVEMAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yahboom_web_savemap_interfaces
{
template <class ContainerAllocator>
struct WebSaveMapRequest_
{
  typedef WebSaveMapRequest_<ContainerAllocator> Type;

  WebSaveMapRequest_()
    : mapname()  {
    }
  WebSaveMapRequest_(const ContainerAllocator& _alloc)
    : mapname(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mapname_type;
  _mapname_type mapname;





  typedef boost::shared_ptr< ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WebSaveMapRequest_

typedef ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<std::allocator<void> > WebSaveMapRequest;

typedef boost::shared_ptr< ::yahboom_web_savemap_interfaces::WebSaveMapRequest > WebSaveMapRequestPtr;
typedef boost::shared_ptr< ::yahboom_web_savemap_interfaces::WebSaveMapRequest const> WebSaveMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator1> & lhs, const ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mapname == rhs.mapname;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator1> & lhs, const ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yahboom_web_savemap_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c4f25b3cd026d312670d09ee1a69f48";
  }

  static const char* value(const ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c4f25b3cd026d31ULL;
  static const uint64_t static_value2 = 0x2670d09ee1a69f48ULL;
};

template<class ContainerAllocator>
struct DataType< ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yahboom_web_savemap_interfaces/WebSaveMapRequest";
  }

  static const char* value(const ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mapname\n"
;
  }

  static const char* value(const ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mapname);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WebSaveMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yahboom_web_savemap_interfaces::WebSaveMapRequest_<ContainerAllocator>& v)
  {
    s << indent << "mapname: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mapname);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YAHBOOM_WEB_SAVEMAP_INTERFACES_MESSAGE_WEBSAVEMAPREQUEST_H
