// Generated by gencpp from file yahboom_web_savemap_interfaces/WebSaveMap.msg
// DO NOT EDIT!


#ifndef YAHBOOM_WEB_SAVEMAP_INTERFACES_MESSAGE_WEBSAVEMAP_H
#define YAHBOOM_WEB_SAVEMAP_INTERFACES_MESSAGE_WEBSAVEMAP_H

#include <ros/service_traits.h>


#include <yahboom_web_savemap_interfaces/WebSaveMapRequest.h>
#include <yahboom_web_savemap_interfaces/WebSaveMapResponse.h>


namespace yahboom_web_savemap_interfaces
{

struct WebSaveMap
{

typedef WebSaveMapRequest Request;
typedef WebSaveMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WebSaveMap
} // namespace yahboom_web_savemap_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yahboom_web_savemap_interfaces::WebSaveMap > {
  static const char* value()
  {
    return "f49bd6f76bfef516e6ae3dd7ae161f79";
  }

  static const char* value(const ::yahboom_web_savemap_interfaces::WebSaveMap&) { return value(); }
};

template<>
struct DataType< ::yahboom_web_savemap_interfaces::WebSaveMap > {
  static const char* value()
  {
    return "yahboom_web_savemap_interfaces/WebSaveMap";
  }

  static const char* value(const ::yahboom_web_savemap_interfaces::WebSaveMap&) { return value(); }
};


// service_traits::MD5Sum< ::yahboom_web_savemap_interfaces::WebSaveMapRequest> should match
// service_traits::MD5Sum< ::yahboom_web_savemap_interfaces::WebSaveMap >
template<>
struct MD5Sum< ::yahboom_web_savemap_interfaces::WebSaveMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yahboom_web_savemap_interfaces::WebSaveMap >::value();
  }
  static const char* value(const ::yahboom_web_savemap_interfaces::WebSaveMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yahboom_web_savemap_interfaces::WebSaveMapRequest> should match
// service_traits::DataType< ::yahboom_web_savemap_interfaces::WebSaveMap >
template<>
struct DataType< ::yahboom_web_savemap_interfaces::WebSaveMapRequest>
{
  static const char* value()
  {
    return DataType< ::yahboom_web_savemap_interfaces::WebSaveMap >::value();
  }
  static const char* value(const ::yahboom_web_savemap_interfaces::WebSaveMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yahboom_web_savemap_interfaces::WebSaveMapResponse> should match
// service_traits::MD5Sum< ::yahboom_web_savemap_interfaces::WebSaveMap >
template<>
struct MD5Sum< ::yahboom_web_savemap_interfaces::WebSaveMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yahboom_web_savemap_interfaces::WebSaveMap >::value();
  }
  static const char* value(const ::yahboom_web_savemap_interfaces::WebSaveMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yahboom_web_savemap_interfaces::WebSaveMapResponse> should match
// service_traits::DataType< ::yahboom_web_savemap_interfaces::WebSaveMap >
template<>
struct DataType< ::yahboom_web_savemap_interfaces::WebSaveMapResponse>
{
  static const char* value()
  {
    return DataType< ::yahboom_web_savemap_interfaces::WebSaveMap >::value();
  }
  static const char* value(const ::yahboom_web_savemap_interfaces::WebSaveMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YAHBOOM_WEB_SAVEMAP_INTERFACES_MESSAGE_WEBSAVEMAP_H
