// Generated by gencpp from file yahboom_web_savemap_interfaces/WebSaveMapResponse.msg
// DO NOT EDIT!


#ifndef YAHBOOM_WEB_SAVEMAP_INTERFACES_MESSAGE_WEBSAVEMAPRESPONSE_H
#define YAHBOOM_WEB_SAVEMAP_INTERFACES_MESSAGE_WEBSAVEMAPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yahboom_web_savemap_interfaces
{
template <class ContainerAllocator>
struct WebSaveMapResponse_
{
  typedef WebSaveMapResponse_<ContainerAllocator> Type;

  WebSaveMapResponse_()
    : response()  {
    }
  WebSaveMapResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WebSaveMapResponse_

typedef ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<std::allocator<void> > WebSaveMapResponse;

typedef boost::shared_ptr< ::yahboom_web_savemap_interfaces::WebSaveMapResponse > WebSaveMapResponsePtr;
typedef boost::shared_ptr< ::yahboom_web_savemap_interfaces::WebSaveMapResponse const> WebSaveMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator1> & lhs, const ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator1> & lhs, const ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yahboom_web_savemap_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yahboom_web_savemap_interfaces/WebSaveMapResponse";
  }

  static const char* value(const ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
"\n"
;
  }

  static const char* value(const ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WebSaveMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yahboom_web_savemap_interfaces::WebSaveMapResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YAHBOOM_WEB_SAVEMAP_INTERFACES_MESSAGE_WEBSAVEMAPRESPONSE_H
